---
title: "Subtypes"
author: "Kornel Kiełczewski"
date: "13 April 2016"
output: html_document
---


```{r}
library(readr)
library(dplyr)
library(reshape2)
source('data-utils.R')
```

PRAD

```{r}
prad <- read_delim('../../download/mrna-rsem-normalized-2015-11-01/gdac.broadinstitute.org_PRAD.Merge_rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.Level_3.2015110100.0.0/PRAD.rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.data.txt', delim = '\t')

raw.counts <- prad[-1,]
raw.counts$HybRefShort <- hyb.ref.short(raw.counts)

tumor.name <- 'PRAD'

data <- get.gene.table(raw.counts, tumor.name, resolve.types = F)$gene.table 
data$`Hybridization REF` <- NULL
r <- rownames(data)
data <- as.data.frame(sapply(data[,-1], as.numeric))
rownames(data) <- r
data <- as.data.frame(t(data))
gene.list <- colnames(data)

# Clinical

subtype.mapping <- read.csv('../../data/PRAD.clinical.tsv', sep = '\t', stringsAsFactors = F) %>% filter(nchar(histological_type) > 0)
data$X_PATIENT <- sub('(\\w+-\\w+-\\w+).*', '\\1', rownames(data))
subtype.data <- data %>% inner_join(subtype.mapping, by = c('X_PATIENT' = 'X_PATIENT'))

b <- data.frame()
for (gene in gene.list) {
  a <- aov(subtype.data[,gene] ~ subtype.data$histological_type)
  t.hsd <- as.data.frame(TukeyHSD(a)$`subtype.data$histological_type`)
  t.hsd$type <- rownames(t.hsd)
  t.hsd$gene <- gene
  b <- rbind(b, dcast(t.hsd, gene ~ type, value.var = c('p adj')))
}

write.table(b, file = '../../subtypes/result-PRAD.clinical.csv', row.names = F, sep = ';')

# Subtypes
subtypes.mapping <- read.csv('../../data/Table_S1_PRAD.csv', sep = ';', stringsAsFactors = F)
data$PATIENT_ID <- sub('(\\w+-\\w+-\\w+).*', '\\1', rownames(data))
subtype.data <- data %>% inner_join(subtypes.mapping, by = c('PATIENT_ID' = 'PATIENT_ID'))

b <- data.frame()
for (gene in gene.list) {
  a <- aov(subtype.data[,gene] ~ subtype.data$Subtype)
  t.hsd <- as.data.frame(TukeyHSD(a)$`subtype.data$Subtype`)
  t.hsd$type <- rownames(t.hsd)
  t.hsd$gene <- gene
  b <- rbind(b, dcast(t.hsd, gene ~ type, value.var = c('p adj')))
}

write.table(b, file = '../../subtypes/result-TABLE_S1_PRAD.csv', row.names = F, sep = ';')


```

THCA Clinical & RNA Subtypes

```{r}
thca <- read_delim('../../download/mrna-rsem-normalized-2015-11-01/gdac.broadinstitute.org_THCA.Merge_rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.Level_3.2015110100.0.0/THCA.rnaseqv2__illuminahiseq_rnaseqv2__unc_edu__Level_3__RSEM_genes_normalized__data.data.txt', delim = '\t')

raw.counts <- thca[-1,]
raw.counts$HybRefShort <- hyb.ref.short(raw.counts)

tumor.name <- 'THCA'

data <- get.gene.table(raw.counts, tumor.name, resolve.types = F)$gene.table 
data$`Hybridization REF` <- NULL
r <- rownames(data)
data <- as.data.frame(sapply(data[,-1], as.numeric))
rownames(data) <- r
data <- as.data.frame(t(data))
gene.list <- colnames(data)

# Clinical
subtype.mapping <- read.csv('../../data/THCA.clinical.tsv', sep = '\t', stringsAsFactors = F) %>% filter(nchar(histological_type) > 0)
data$X_PATIENT <- sub('(\\w+-\\w+-\\w+).*', '\\1', rownames(data))
subtype.data <- data %>% inner_join(subtype.mapping, by = c('X_PATIENT' = 'X_PATIENT'))

b <- data.frame()
for (gene in gene.list) {
  a <- aov(subtype.data[,gene] ~ subtype.data$histological_type)
  t.hsd <- as.data.frame(TukeyHSD(a)$`subtype.data$histological_type`)
  t.hsd$type <- rownames(t.hsd)
  t.hsd$gene <- gene
  b <- rbind(b, dcast(t.hsd, gene ~ type, value.var = c('p adj')))
}

write.table(b, file = '../../subtypes/result-THCA.clinical.csv', row.names = F, sep = ';')


# Subtypes
subtype.mapping <- read.csv('../../data/THCA_RNA_Subtypes.tsv', sep = '\t', stringsAsFactors = F)
subtype.mapping$New_RNA_Class <- as.factor(subtype.mapping$New_RNA_Class)
data$Barcode <- gsub('-', '.', data$X_PATIENT)
subtype.data <- data %>% inner_join(subtype.mapping, by = c('Barcode' = 'Barcode'))

b <- data.frame()
for (gene in gene.list) {
  a <- aov(subtype.data[,gene] ~ subtype.data$New_RNA_Class)
  t.hsd <- as.data.frame(TukeyHSD(a)$`subtype.data$New_RNA_Class`)
  t.hsd$type <- rownames(t.hsd)
  t.hsd$gene <- gene
  b <- rbind(b, dcast(t.hsd, gene ~ type, value.var = c('p adj')))
}

write.table(b, file = '../../subtypes/result-THCA_RNA_Subtypes.csv', row.names = F, sep = ';')

```

